stages:
  read_raw_data:
    cmd: python dvc_scripts/read_raw_data.py --output-file ./data/raw/raw_data.pkl
    deps:
    - ./src/data/read_raw_data.py
    - ./dvc_scripts/read_raw_data.py
    params:
    - read_raw_data.end_id
    - read_raw_data.start_id
    outs:
    - ./data/raw/raw_data.pkl
  train_test_split:
    cmd: python dvc_scripts/train_test_split.py --raw-input-file ./data/raw/raw_data.pkl
      --train-output-file ./data/train_test_split/train.pkl --test-output-file ./data/train_test_split/test.pkl
    deps:
    - ./data/raw/raw_data.pkl
    - ./dvc_scripts/read_raw_data.py
    - ./src/train_test_split/train_test_split.py
    params:
    - train_test_split.random_state
    - train_test_split.test_size
    outs:
    - ./data/train_test_split/test.pkl
    - ./data/train_test_split/train.pkl
  train_basic_logistic_regression:
    cmd: python ./dvc_scripts/basic_logistic_regression.py --train-input-file ./data/train_test_split/train.pkl
      --model-output-file models/basic_logistic_regression/model.pkl --metrics-output-file
      metrics/basic_logistic_regression/train.json
    deps:
    - ./data/train_test_split/train.pkl
    - ./dvc_scripts/basic_logistic_regression.py
    - ./src/models/basic_logistic_regression.py
    params:
    - model.basic_logistic_regression.classifier_settings
    - model.basic_logistic_regression.features
    outs:
    - ./models/basic_logistic_regression/model.pkl
    metrics:
    - ./metrics/basic_logistic_regression/train.json:
        cache: false
